### ISSUE TITLE
早些使用OpenJDK, 生活会很美好

### ISSUE THREAD

**Issue by larryw3i** [shenxiangzhuang/PythonDataAnalysis#1]
**早些使用OpenJDK, 生活会很美好**
**所以我建议作者在第8页教大家安装的是OpenJDK, 而不是OracleJDK**
[Oracle Technology Network License Agreement for Oracle Java SE](https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html) >>
Further, You may not:
-    use the Programs for any data processing or any commercial, production, or internal business purposes other than developing, testing, prototyping, and demonstrating your Application;
-    remove or modify any Program markings or any notice of Oracle’s or a licensor’s proprietary rights;
-    make the Programs available in any manner to any third party (other than Contractors acting on Your behalf as set forth in this Agreement);
-    assign this Agreement or distribute, give, or transfer the Programs or an interest in them to any third party, except as expressly permitted in this Agreement for Contractors (the foregoing shall not be construed to limit the rights You may otherwise have with respect to Separately Licensed Third Party Technology);
-    cause or permit reverse engineering (unless required by law for interoperability), disassembly or decompilation of the Programs; and
-    create, modify, or change the behavior of, classes, interfaces, or subpackages that are in any way identified as "java", "javax", "sun", “oracle” or similar convention as specified by Oracle in any naming convention designation.

**一直使用OpenJDK, 从未改变>>**
[AdoptOpenJDK](https://adoptopenjdk.net/)

**Comment by shenxiangzhuang** [comment]
感谢你的提醒，他们的差别确实没有研究过，后面有时间我会详细看下，如果书有机会再版的话会考虑改进相关内容。
