### ISSUE TITLE
利用正则表达式提取百度首页关键词

### ISSUE THREAD

**Issue by Herrwangistcool** [shenxiangzhuang/PythonDataAnalysis#12]
章节：2.3.6 正则表达式入门
书中源码：“  
import re
import requests
from fake_useragent import UserAgent

ua = UserAgent()
headers = {'User-Agent': ua.random}
# headers = {}
html = requests.get('https://www.baidu.com/', headers=headers)
html.encoding = 'utf-8'
html = html.text
# print(html)
titles = re.findall(r'<a href="(http://.*?.com)" name="tj_tr.*?" class="mnav">(\w{2})</a>', html)
print(titles)”
利用此源码获取的网页内容已不能正常提取关键字，print出来的内容变成了像<a href="http://tieba.baidu.com/f?fr=wwwt"  wdfield="kw"  onmousedown="return c({'fm':'tab','tab':'tieba'})"  class="s-tab-item s-tab-tieba">贴吧</a>这样的内容，需要重新编辑正则式。

**Comment by shenxiangzhuang** [comment]
感谢反馈。这个应该是因为最近百度改了首页的源码，我这里简单改了下。用`re.findall(r'<a href="(http://.*?.com)" .*? class="mnav.*?">(\w{2})</a>', html)`是可以得到如下输出的：
```python
[('http://news.baidu.com', '新闻'),
 ('http://map.baidu.com', '地图'),
 ('http://tieba.baidu.com', '贴吧'),
 ('http://xueshu.baidu.com', '学术')]
```

**Comment by Herrwangistcool** [comment]
谢谢楼主，该问题已解决。
