### ISSUE TITLE
书籍第五章，定制新闻服务的爬虫 url = http://tech.baidu.com/失效

### ISSUE THREAD

**Issue by yizelsj** [shenxiangzhuang/PythonDataAnalysis#13]

**Comment by shenxiangzhuang** [comment]
@ispenser-byte 感谢反馈，链接确实已经失效，看了下应该是已经迁移到了`https://news.baidu.com/tech`, 后续我看下怎么补充一下替代的方案吧。

**Comment by shenxiangzhuang** [comment]
@ispenser-byte 你好，这个问题已经修复了哈，只需要把URL改成上面新的URL即可, 其他部分不用动, 具体见#15. 很抱歉那么晚才修复这个问题，后续有问题欢迎继续反馈.

**Comment by shenxiangzhuang** [comment]
@ispenser-byte 不知道是否解决了你这边的问题, 没问题的话我就先close了
