### ISSUE TITLE
关于豆瓣登陆的问题

### ISSUE THREAD

**Issue by kenneth663** [shenxiangzhuang/PythonDataAnalysis#2]
mydata = soup.select('#display')[0].get_text()
IndexError: list index out of range
这一行出现了错误

**Comment by shenxiangzhuang** [comment]
你好，不知道你说的哪个文件？我刚才测试了一下`douban_login.py`，我这里是正常的，并没有复现你的错误。你这里的错误可能是因为没有正常登录，所以获取登录后的内容会出错，可以尝试着把Github上的示例代码填上自己的帐号密码直接运行下看看。

**Comment by kenneth663** [comment]
是豆瓣登陆的那个文件,错误是这个变量mydata = soup.select('#display')[0].get_text(),我试着用xpath解析一下吧

**Comment by shenxiangzhuang** [comment]
之前是没有问题的，现在豆瓣的登录界面更新了， 原来的代码已经登录不上了，所以会重新导致上面的问题。新的登录方式可以查看同文件夹下新添加的`douban_login_new.py`文件。
