### ISSUE TITLE
豆瓣邮箱注册不了，只能手机验证码登陆

### ISSUE THREAD

**Issue by chengyue0** [shenxiangzhuang/PythonDataAnalysis#4]
在2.3.7模拟登陆的，页码是70页。需要提交表单数据登陆。您书里使用的是邮箱账号密码登陆。现在豆瓣网不支持邮箱注册了。我只能通过手机验证码登陆。我试着提交表单数据，但是都登陆不了。网页源码也和书上的变动挺大的。想向您请教一下。

**Comment by shenxiangzhuang** [comment]
你好，首先手机注册后绑定邮箱后同样可以用邮箱登录的。此外， 现在豆瓣的登录界面更新了， 原来的代码已经登录不上了， 新的登录方式可以查看同文件夹下新添加的`douban_login_new.py`文件。

**Comment by shenxiangzhuang** [comment]
简单说一下几个读者在邮件的问题和最新的登录方法说明。

1. 手机号注册的问题
好像现在注册豆瓣只能用手机号码，这其实关系不大。只要注册后再绑定邮箱就可以用邮箱登录了。

2. 抓不到登录豆瓣的post数据包
这是因为页面自动跳转了，可以在F12后在右上角勾选`Preserve log`， 火狐和谷歌浏览器均可：

火狐
![image](https://user-images.githubusercontent.com/17157965/57005282-53ec2080-6c09-11e9-98dd-ce4489acfe28.png)

Chrome
![image](https://user-images.githubusercontent.com/17157965/57005288-6bc3a480-6c09-11e9-8edb-8d5aa537198d.png)


3. 新的变化
仔细对比下新旧登录文件就可以看出来改变的主要就是提交的表单内容，将表单重新构造即可。此外，测试的时候发现一个UA用多了也会出现登录不上的问题，注意改下就好。

**Comment by chengyue0** [comment]
嗯，好的。我测试一下。谢谢

**Comment by chengyue0** [comment]
谢谢您的及时回复。困扰我的问题解决了
