### ISSUE TITLE
有关代码的问题

### ISSUE THREAD

**Issue by hxy12345** [shenxiangzhuang/PythonDataAnalysis#6]
你好，我想知道这是要抓取什么mydata = soup.select('#display')[0].get_text()？我去网页源代码看了下没有找到id=#display的

**Comment by shenxiangzhuang** [comment]
![image](https://user-images.githubusercontent.com/17157965/58815688-a5e5f300-865a-11e9-964b-d40d39d0d82b.png)
不知能否回答你的问题？
ps：提问时请注明书的版次及页码，或者是代码文件名及对应行数。至于获取不到是因为豆瓣页面做了改动，具体参考 #4

**Comment by hxy12345** [comment]
我想知道那行代码作用是什么？ （#display）是什么？

**Comment by shenxiangzhuang** [comment]
是用于获取签名的selector(旧版网页中)，因为现在页面改了，所以找不到了。
