### ISSUE TITLE
豆瓣请求报错

### ISSUE THREAD

**Issue by lyj14736** [shenxiangzhuang/PythonDataAnalysis#7]
麻烦看下请求豆瓣之后，安装咋们的新代码，添加邮箱，密码登录就报错(https://user-images.githubusercontent.com/45935304/61353481-84576880-a8a2-11e9-8e85-2771706ea2b6.png)

**Comment by shenxiangzhuang** [comment]
我这里测试是没有问题的，你可能操作出了问题。
首先，确定是用的最新的代码吗？ 其次，如果是用了最新的代码，首次运行记得把之前的`cookies.douban`文件删掉，因为那是旧的代码生成的，已经失效。

**Comment by lyj14736** [comment]
感谢指点，用GitHub上的新代码清理过cookies是可以执行的，按书上的代码还是有点问题，在那几个地方报错，能否告知什么原因呢




------------------ 原始邮件 ------------------
发件人: "XiangzhuangShen"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 下午3:14
收件人: "shenxiangzhuang/PythonDataAnalysis"<PythonDataAnalysis@noreply.github.com>;
抄送: ""<1837178394@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shenxiangzhuang/PythonDataAnalysis] 豆瓣请求报错 (#7)




我这里测试是没有问题的，你可能操作出了问题。
 首先，确定是用的最新的代码吗？ 其次，如果是用了最新的代码，首次运行记得把之前的cookies.douban文件删掉，因为那是旧的代码生成的，已经失效。

**Comment by shenxiangzhuang** [comment]
> 仔细对比下新旧登录文件就可以看出来改变的主要就是提交的表单内容，将表单重新构造即可。此外，测试的时候发现一个UA用多了也会出现登录不上的问题，注意改下就好。

可以参考下其他closed掉的issue(#2), 基本都是讨论这个问题。

**Comment by lyj14736** [comment]
感谢感谢，刚开始看您的书，再学习学习，研究下




------------------ 原始邮件 ------------------
发件人: "XiangzhuangShen"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 下午4:03
收件人: "shenxiangzhuang/PythonDataAnalysis"<PythonDataAnalysis@noreply.github.com>;
抄送: ""<1837178394@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shenxiangzhuang/PythonDataAnalysis] 豆瓣请求报错 (#7)



 
仔细对比下新旧登录文件就可以看出来改变的主要就是提交的表单内容，将表单重新构造即可。此外，测试的时候发现一个UA用多了也会出现登录不上的问题，注意改下就好。
  
可以参考下其他closed掉的issue, 基本都是讨论这个问题。
